### PR TITLE
New recipe to run Android Unit Tests in parallel in Multimodule project

### PR DESCRIPTION
**Pull request by ferPrieto**

### CODE REVIEW

**Comment by godrei** [comment]
Hi @ferPrieto , first of all, thanks for the contribution!

As far as I see, we have a very similar recipe to this new one: https://github.com/bitrise-io/workflow-recipes/blob/main/recipes/android-parallel-testing-unit-test-shards.md.

What are the key differences in your recipe compared to the existing one? Would be great to keep one recipe per scenario, to support users in finding the best bitrise configuration.

**Comment by ferPrieto** [comment]
Hey @godrei, it looks similar but the one you sent clones the project in each stage, which makes it not efficient in a real project. 

In mine it clones the project, zips and deploys it on Bitrise in one stage and then in the next stage it's able to run in parallel the project accessing the deployed files directly (pulling the intermediate files). Which it actually works efficiently in a production project.

**Comment by godrei** [comment]
I see, thank you.

I wanted to test this, but following the instructions leads to a failing build. May I ask you to update it to produce a green build?
This is what I spotted sofar:
- `clone_and_deploy_to_bitrise` workflow references `PROJECT_LOCATION` env var, but it doesn't have a value
- the `unit_tests_module_x` workflows use modules and variant that doesn't exist in the sample project: https://github.com/bitrise-io/Bitrise-Android-Modules-Sample.git
- also, I suggest adding the module and variant name as suffixes to the `unit_tests_module_x` workflow, like: `unit_tests_module_app_debug`

**Comment by ferPrieto** [comment]
Thanks for the comments @godrei, I've just pushed some updates regarding what you mentioned 😄

**Comment by ofalvai** [comment]
Hello @ferPrieto 👋 

We did a more thorough review of this workflow pattern and realized that moving the git source tree across builds is something that we don't want to recommend officially. It's great if it works in your setup, but we have a few reasons why it might not be for everyone:

- It might be a security concern for someone to persist source code outside of the build VMs. CI systems (including Bitrise) by default only store the source code inside the ephemeral VMs, which are destroyed when the build completes.
- In our experience, zipping and moving the git source tree across the network is often slower than doing a shallow clone (which only checks out the latest commit). Of course, it depends on a lot of factors, such as the number of files in the repo and the overall size, so it's possible that it works for some.
- While we don't limit the size of build artifacts at the moment, uploading a large zipped git tree would put a lot of strain on Bitrise systems, so we can't recommend this without considering the repo size.

Again, if this workflow recipe works for your use case, then it's completely fine to continue using it. But we don't want to recommend this usage pattern officially through the recipes.

I'm sorry we didn't flag this earlier, we appreciate your contribution regardless 💜

**Pull request closed without merging**
